### ISSUE TITLE
Please tag releases on Git

### ISSUE THREAD

**Issue by mweinelt** [rhasspy/gruut-ipa#3]
Hi, thanks for working on everything Rhasspy, much appreciated.

If you could use Git tags on this repository to publish new versions we could better reference and update this package in downstream Linux distros.

Thanks for considering!

**Comment by mweinelt** [comment]
PyPi release is 0.10.0, no matching Git tag :cry:

**Comment by synesthesiam** [comment]
Got tags updated. Sorry!
